services:
  app_vendas:
    build: apiwdpvendas
    mem_limit: 512m
    ports:
      - "9475:9475"
    environment:
      DB_URL: jdbc:mysql://wdpvendas:3306/db_loja?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      wdpvendas:
        condition: service_healthy

  wdpvendas:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db_loja
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: wdpvendas
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    depends_on:
      wdpvendas:
        condition: service_healthy
